apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:              # ⭐ 어떤 Deployment를 조절할지
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment     # Deployment의 metadata.name과 일치해야 함
  minReplicas: 2               # 최소 Pod 수
  maxReplicas: 5               # 최대 Pod 수
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70